### ISSUE TITLE
Can I use bootstrap?

### ISSUE THREAD

**Issue by Jiihwan-Kim** [Huelse/HEAAN-Python#5]
After several days of testing, I concludes that this code is very useful for testing heaan in python.
But when I tried to bootstrap, an "IndexError:map::at" error occured.
Can someone help me by checking the normal working of bootstrap?

**Comment by Huelse** [comment]
Can you post the error?
Try to validate the code in c++.

**Comment by Jiihwan-Kim** [comment]
Oh, it works fine now. It was caused by not adjusting logq in bootstrapAndEqual function.
But I still can't understand what logq or logp do in this algorithm. Can you recommend a paper?

**Comment by Huelse** [comment]
You can refer to these issues from HEAAN [28](https://github.com/snucrypto/HEAAN/issues/28), [51](https://github.com/snucrypto/HEAAN/issues/51) or the paper [https://eprint.iacr.org/2018/153.pdf](https://eprint.iacr.org/2018/153.pdf).

**Comment by Jiihwan-Kim** [comment]
Thanks a lot!!
